// Code generated by cli/gen/get.go. DO NOT EDIT.

package cli

import (
    "fmt"

    "github.com/devkvlt/hexer"
    "github.com/urfave/cli/v2"
)

var blue = cli.Command{
	Name:        "blue",
	Usage:       "Get the blue component",
	Description: "Get the (0-255)-based blue component of the input color in the RGB model.",
	UsageText:   "hexer blue <color>",
    Action: func(ctx *cli.Context) error {
		name := ctx.Command.FullName()
		errStr := fmt.Sprintf("command %q expects a hex color", name)
		if ctx.NArg() != 1 {
			return cli.Exit(errStr, 1)
		}
		c := ctx.Args().Get(0)
		x, err := hexer.Blue(c)
		if err != nil {
			return cli.Exit(err, 1)
		}
		fmt.Println(x)
		return nil
    },
}