// Code generated by cli/genmodify.go. DO NOT EDIT.

package cli

import (
	"fmt"
	"strconv"

	"github.com/devkvlt/hexer"
	"github.com/urfave/cli/v2"
)

var darken = cli.Command{
	Name:        "darken",
	Usage:       "Darken",
	Description: "Darken a color by subtracting the given amount from its (0-100)-based lightness component in the HSL model.",
	UsageText:   "hexer darken <color> <amount>",
	Action: func(ctx *cli.Context) error {
		argc := ctx.NArg()
		args := ctx.Args()
		name := ctx.Command.FullName()
		errStr := fmt.Sprintf("command %q expects a hex color and a number", name)
		if argc != 2 {
			return cli.Exit(errStr, 1)
		}
		a, err := strconv.ParseFloat(args.Get(1), 64)
		if err != nil {
			return cli.Exit(errStr, 1)
		}
		c := args.Get(0)
		c_, err := hexer.Darken(c, a)
		if err != nil {
			return cli.Exit(err, 1)
		}
		fmt.Println(c_)
		return nil
	},
}