// Code generated by cli/gen/get.go. DO NOT EDIT.

package cli

import (
    "fmt"

    "github.com/devkvlt/hexer"
    "github.com/urfave/cli/v2"
)

var luminance = cli.Command{
	Name:        "luminance",
	Usage:       "Get the luminance",
	Description: "Get the relative luminance of the input color, i.e. the Y component in the XYZ model.",
	UsageText:   "hexer luminance <color>",
    Action: func(ctx *cli.Context) error {
		name := ctx.Command.FullName()
		errStr := fmt.Sprintf("command %q expects a hex color", name)
		if ctx.NArg() != 1 {
			return cli.Exit(errStr, 1)
		}
		c := ctx.Args().Get(0)
		x, err := hexer.Luminance(c)
		if err != nil {
			return cli.Exit(err, 1)
		}
		fmt.Println(x)
		return nil
    },
}