name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Run tests
        uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - run: go build
